/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IWhitelist, IWhitelistInterface } from "../IWhitelist";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "whitelistedAddresses",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWhitelist__factory {
  static readonly abi = _abi;
  static createInterface(): IWhitelistInterface {
    return new utils.Interface(_abi) as IWhitelistInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWhitelist {
    return new Contract(address, _abi, signerOrProvider) as IWhitelist;
  }
}
